Kevins erster Pull-Request
TheDonDope/kindergarten pull request #1
Opened 2017-08-15 20:37 UTC by Pictarin

Hallo TheDonDope,

bitte mach mal ein Review fuer meinen Code, danke.

2017-08-15 20:37 UTC, TheDonDope commented
Hallo Kevin,

okay schaue ich mir an

2017-08-15 20:38 UTC, TheDonDope commented on build.gradle
> + * For more details take a look at the Java Libraries chapter in the Gradle
Test kommentar

2017-08-15 20:39 UTC, Pictarin commented on build.gradle
> + * For more details take a look at the Java Libraries chapter in the Gradle
Aeh, was soll ich hier machen?

2017-08-23 18:14 UTC, TheDonDope requested changes
Siehe Kommentare,

insgesamt arbeitest du haeufig mit Vererbung von Panels, was Du aber garnicht brauchst. Du willst ein Panel einfach benutzen.

Ich committe mal was dazu, schau mal #3

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/App.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/App.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/App.java
> +/*
Den auskommentierten Code rausschmeissen, schreib dir das irgendwo anders nieder, oder schreibs ins README.md

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/ConfigBtn.java
> +public class ConfigBtn extends JPanel {
Naja, eingentlich ist das ja kein Config*Button* mehr, sondern ein Panel mit zwei Buttons.
Also bennen es doch in ConfigPanel um.

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/ConfigBtn.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/ConfigBtn.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Menu.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Menu.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Menu.java
> +    /// Positionierung der Toolbar///
Kommentare entweder im Format

```java
// Einzeiliges kommentar
```

oder 

```java
/** 
 * Mehrzeiliges
 * Kommentar
 */

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/NavigationsBtn.java
> +public class NavigationsBtn extends JPanel implements ActionListener {
Auch hier ist das kein *Button* mehr, sondern ein Panel -> Umbenennen in NavigationPanel z.B.

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/NavigationsBtn.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/NavigationsBtn.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/PersonTableModel.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/ShowFenster.java
> +public class ShowFenster extends JPanel {
Ist auch kein Fenster, sondern ein Panel - wie waere es mit `MainPanel` ?

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/TablePanel.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/TablePanel.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/TextPanel.java
> +  public TextPanel() {
Leerzeile fehlt, Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/TextPanel.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/TextPanel.java
> +  public void appendText(String text) {
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Toolbar.java
> +public class Toolbar extends JPanel implements ActionListener{
besser: `ToolbarPanel`

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Toolbar.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/Toolbar.java
> +  public Toolbar() {
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/VerkaeuferErfassung.java
> +
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/VerkaeuferErfassung.java
> +    public VerkaeuferErfassung() {
Javadoc hinzufuegen

2017-08-23 18:14 UTC, TheDonDope commented on src/main/java/de/clearit/kindergarten/VerkaeuferErfassung.java
> +public class VerkaeuferErfassung extends JPanel{
besser: `VerkaeuferErfassungPanel`

2017-08-24 06:26 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/App.java
> +/*
erledigt

2017-08-24 06:28 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/Menu.java
> +    /// Positionierung der Toolbar///
meinst du hier das /// KOMMENTAR ///?

Das war für mich zur Übersicht hebt sich besser raus -> finde ich :)

2017-08-24 06:29 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/ShowFenster.java
> +public class ShowFenster extends JPanel {
habe es in ShowPanel umbenannt - erklär ich dir im Statusmeeting

2017-08-24 06:29 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/TextPanel.java
> +  public TextPanel() {
TextPanel war nur ein Lückenfüller existiert nicht mehr :)

2017-08-24 06:30 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/Toolbar.java
> +public class Toolbar extends JPanel implements ActionListener{
erledigt - macht auch mehr sinn :)

2017-08-24 06:31 UTC, Pictarin commented on src/main/java/de/clearit/kindergarten/VerkaeuferErfassung.java
> +public class VerkaeuferErfassung extends JPanel{
check

2017-09-20 15:13 UTC, closed without merging